config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  # get 'sessions/new'
  # get 'tasks/index'

  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks

  resources :users, only: [:new, :create,:show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :labels

  resources :tasklabels, only: [:create, :destroy]
end

app/models/task.rb
class Task < ApplicationRecord

  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :time_limit, presence: true
  # 未着手0,着手中1,完了2にした
  enum status:{waiting: 0, working: 1, completed: 2}
  enum priority:{low: 0, middle: 1, high: 2}

  scope :serch_title, -> (title) { where(title: title) }
  scope :serch_status, -> (status) { where(status: status) }

  scope :serch_label, -> (label) {
    where(id:
      Tasklabel.where(label_id: label).map{|tasklabel| tasklabel.task_id }
    )
  }

  scope :time_limit, -> { all.order(time_limit: :desc) }
  scope :priority, -> { all.order(priority: :desc) }
  scope :created_at, -> { all.order(created_at: :desc) }

  paginates_per 10

  belongs_to :user

  has_many :tasklabels, dependent: :destroy
  has_many :tasklabel_labels, through: :tasklabels, source: :label
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
   before_action :set_task, only: [:show, :edit, :update, :destroy]

  def new
    @task = Task.new
    @labels = Label.all
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save

      if tasklabel_params[:label_ids]
        tasklabel_params[:label_ids].each do |t|
          @tasklabel = @task.tasklabels.new(label_id: t)
          @tasklabel.save
        end
      end
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to tasks_path, notice: "タスク作成しました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
  end

  def index
    if params[:search]
      task_searchs
    else
      task_sorts
    end
  end

  def show
    @tasklabel = @task.tasklabel_labels
  end

  def edit
    @labels = Label.all
  end

  def update
    if @task.update(task_params)

        if tasklabel_params[:label_ids]
          @task.tasklabels.destroy_all
          tasklabel_params[:label_ids].each do |t|
            @tasklabel = @task.tasklabels.new(label_id: t)
            @tasklabel.save
          end
        end
      redirect_to tasks_path, notice: "タスクを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました！"
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :time_limit, :status, :priority)
  end

  def tasklabel_params
    params.require(:task).permit({ label_ids: [] })
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_searchs
    @tasks = current_user.tasks

    if params[:title].present?
      @tasks = @tasks.serch_title(params[:title])
    end

    if params[:status].present?
      @tasks = @tasks.serch_status(params[:status])
    end

    if params[:label].present?
      @tasks = @tasks.serch_label(params[:label])
    end

    @tasks = @tasks.page(params[:page])

  end

  def task_sorts
    if params[:sort_expired]
      # @tasks = Task.all.order(time_limit: :desc)
      @tasks = current_user.tasks.page(params[:page]).time_limit
    elsif params[:sort_priority]
      # @tasks = Task.all.order(priority: :desc)
      @tasks = current_user.tasks.page(params[:page]).priority
    else
      # @tasks = Task.all.order(created_at: :desc)
      # @tasks = Task.created_at
      @tasks = current_user.tasks.page(params[:page]).created_at
    end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="task_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="task_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="task_title">
    <%= form.label :time_limit %>
    <%= form.date_select :time_limit %>
  </div>
  <div class="task_title">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses.keys.to_a %>
  </div>
  <div class="task_title">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities.keys.to_a %>
  </div>

  <% @labels.each do |label| %>
    <div>
      <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
      <%= label.label_title %>
    </div>
  <% end %>

  <%= form.submit :登録する %>
<% end %>

<%= link_to 'タスク一覧画面にもどる', tasks_path %>

app/views/tasks/edit.html.erb
<h2>タスクを作成する</h2>

  <%= render 'form' %>

app/views/tasks/index.html.erb
<div class="container">

  <h1 class="main_title">タスク一覧</h1>
  <p><%= notice %></p>

    <%= form_with(url: tasks_path, method: :get, local: true) do |f| %>
      <table class="serch">
        <ul class="row">
          <li class="col-md-3">
            <%= f.label :title, 'タイトル検索' %>
            <%= f.text_field :title %>
          </li>

          <li class="col-md-5">
            <%= f.label :status, 'ステータス検索' %>
            <%= f.select :status, Task.statuses.map{ |k, v| [k,v]}, include_blank: true %>
          </li>

          <li class="col-md-3">
            <%= f.label :label, 'ラベル検索' %>

            <%= f.select :label, options_from_collection_for_select(Label.all, :id, :label_title), include_blank: true %>
          </li>

          <%= f.hidden_field :search, value: 'true' %>

          <li class="col-md-1">
            <%= f.submit '検索' %>
          </li>
        </ul>
      </table>
    <% end %>

  <% if params[:search] == "true" %>
    <%= link_to '戻る', tasks_path %>
  <% end %>

  <table>
    <ul class="row">
      <% if params[:search] != "true" %>
        <li class="col-md-2"><%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %></li>
        <li class="col-md-2"><%= link_to "優先順位でソートする", tasks_path(sort_priority: "true") %></li>
        <li class="col-md-2"><%= link_to 'ソートを戻す', tasks_path %></li>
      <% end %>
    </ul>
  </table>

  <%#= page_entries_info @tasks %>

  <%#= paginate @tasks %>

  <table>
    <tr class="row">
      <th class="col-md-2">タイトル</th>
      <th class="col-md-2">内容</th>
      <th class="col-md-2">終了期限</th>
      <th class="col-md-2">ステータス</th>
      <th class="col-md-1">優先順位</th>
    </tr>

    <% @tasks.each do |task| %>
      <tr class="row">
        <td class="col-md-2"><%= task.title %></td>
        <td class="col-md-2"><%= task.content %></td>
        <td class = "index" class="col-md-2"><%= task.time_limit %></td>
        <td class="col-md-2"><%= task.status %></td>
        <td class = "priority" class="col-md-1"><%= task.priority %></td>
        <td><button type="button" class="btn btn-success"><%= link_to '詳細確認', task_path(task.id) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to "タスク編集", edit_task_path(task.id), data: { confirm: '本当に編集していいですか？' } %></button></td>
        <td><button type="button" class="btn btn-danger"><%= link_to 'タスク削除', task_path(task.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></button></td>
      </tr>
    <% end %>
  </table>


  <%= link_to '新しくタスクを投稿する', new_task_path %>

</div>

app/views/tasks/new.html.erb
<h2>タスクを作成する</h2>

  <%= render 'form' %>

app/views/tasks/show.html.erb
<h1>タスク詳細画面</h1>
<p>タイトル: <%= @task.title %></p>
<p>内容: <%= @task.content %></p>
<p>終了期限: <%= @task.time_limit %></p>
<p>ステータス: <%= @task.status %></p>
<p>優先順位: <%= @task.priority %></p>

<hr>

<table>
  <tr>
    <th>ラベル</th>
  </tr>

  <% @tasklabel.each do |label| %>
    <tr>
      <td><%= label.label_title %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'タスク一覧画面にもどる', tasks_path %>