config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  # get 'sessions/new'
  # get 'tasks/index'

  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks

  resources :users, only: [:new, :create,:show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :labels

  resources :tasklabels, only: [:create, :destroy]
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :tasklabels, dependent: :destroy
  has_many :tasklabel_tasks, through: :tasklabel, source: :task
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
before_action :require_admin

  def new
    @label = Label.new
  end

  def index
    @labels = Label.all
  end

  def create
    @label = Label.new(label_params)

    if @label.save
      redirect_to labels_path, notice: "ラベル「#{@label.label_title}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @label = Label.find(params[:id])
  end

  def update
    @label = Label.find(params[:id])

    if @label.update(label_params)
      redirect_to labels_path, notice: "ラベル「#{@label.label_title}」を登録しました。"
    else
      render :new
    end
  end

  def destroy
    @label = Label.find(params[:id])
    @label.destroy
    redirect_to labels_path, notice: "ラベル「#{@label.label_title}」を削除しました。"
  end

  private

  def label_params
    params.require(:label).permit(:label_title)
  end

  def require_admin
    render :custom_error unless current_user.admin?
  end

end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: @label, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :label_title, 'ラベルタイトル' %>
    <%= f.text_field :label_title, class: 'form-control' %>
  </div>
  <%= f.submit "登録する", class: 'btn btn-primary' %>
<% end %>

<%= link_to 'ラベル一覧画面', labels_path %>

app/views/labels/custom_error.html.erb
<h2>タスク一覧画面へ移動してください</h2>

<td><%= link_to 'タスク一覧画面', tasks_path %></td>

app/views/labels/edit.html.erb
<h1>タスクの編集</h1>
<%= render 'form' %>

app/views/labels/index.html.erb
<h1>ラベル一覧（管理者用）</h1>

<%= link_to '新規登録', new_label_path, class: 'btn btn-primary' %>
<%= link_to 'ユーザー一覧画面（管理者用）', admin_users_path %>

<table>
  <tr>
    <th>ラベル</th>
  </tr>

  <% @labels.each do |label| %>
    <tr>
      <td><%= label.label_title %></td>
      <td><%= link_to "ラベルを編集する", edit_label_path(label.id), data: { confirm: '本当に編集していいですか？' } %></td>
      <td><%= link_to 'ラベルを削除する', label_path(label.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    </tr>
  <% end %>
</table>

app/views/labels/new.html.erb
<h1>新規作成</h1>
<%= render 'form' %>