config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  # get 'sessions/new'
  # get 'tasks/index'

  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks

  resources :users, only: [:new, :create,:show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :labels

  resources :tasklabels, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :ensure_admin
  has_many :tasks, dependent: :destroy

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation {email.downcase!}

  has_secure_password
  validates :password_digest, presence: true, length: { minimum: 6 }

  private

  def ensure_admin
    throw(:abort) if admin? && User.where(admin: "true").count <= 1
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required
  before_action :require_admin
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
  end

  def index
    @users = User.all.includes(:tasks)
    # @users = User.all
    # @tasks = Task.all
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を削除しました。"
    else
      redirect_to admin_users_path, notice: "管理者「#{@user.name}」は削除できません。管理者は最低1人以上ログインしていなければいけません。"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
    render :custom_error unless current_user.admin?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required
  def new
    redirect_to user_path(current_user.id) if current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if  @user.save
      session[:user_id] = @user.id
      #新規登録した後、showにidを飛ばしてログインする
      redirect_to user_path(@user.id)
    else
      render'new'
    end
  end

  def show
    redirect_to user_path(current_user.id) if current_user.id != params[:id].to_i
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with model: [:admin, @user], local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-check">
    <%= f.label :admin, class: 'form-check-label'  %>
      <%= f.check_box :admin, class: 'form-check-input' %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit "登録する", class: 'btn btn-primary' %>
<% end %>

<%= link_to '一覧画面にもどる', admin_users_path %>

app/views/admin/users/custom_error.html.erb
<h2>管理者権限がありませんのでアクセスできません</h2>

app/views/admin/users/edit.html.erb
<h1>ユーザーの編集</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧（管理者用）</h1>

<%= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary' %>
<%= link_to 'ラベル一覧画面（管理者用）', labels_path %>


<table>
  <tr>
    <th>名前</th>
    <th>メール</th>
    <th>管理者</th>
    <th>id</th>
    <th>投稿数</th>
    <th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.admin? ? 'はい' : 'いいえ' %></td>
      <td>[<%= user.id %>]</td>
      <td>{<%= user.tasks.count %>}</td>
      <td><%= link_to '詳細を確認する', admin_user_path(user.id) %></td>
      <td><%= link_to "ユーザーを編集する", edit_admin_user_path(user.id), data: { confirm: '本当に編集していいですか？' } %></td>
      <td><%= link_to 'ユーザーを削除する', admin_user_path(user.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    </tr>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<h1>ユーザー登録</h1>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ（管理用）</h1>

<%= link_to '一覧画面にもどる', admin_users_path %>

<p>id: <%= @user.id %></p>
<p>名前: <%= @user.name %></p>
<p>メールアドレス: <%= @user.email %></p>
<p>管理者: <%= @user.admin? ? 'はい' : 'いいえ' %></p>


<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>終了期限</th>
    <th>ステータス</th>
    <th>優先順位</th>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.time_limit %></td>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
    </tr>
  <% end %>
</table>